name: temporary_jni_test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jniexample:
    name: jni_tests
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - run: bazel test --test_output=all //test:app_test
        name: 'Run JNI example test'

